sudo: false
language: node_js
node_js:
  - '4'
  - '5'
  - '6'
script:
  - node --version
  - npm --version
  # linting
  - npm run lint
  # nodejs testing
  - npm run cover
after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
